/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Gestiones.*;

/**
 *
 * @author Carlos Salgado
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Instancias de las gestiones
     */
     public static GestionAula gAula=new GestionAula();
     public static GestionCampoEstudio gCampoEstudio=new GestionCampoEstudio();
     public static GestionCarreraDeEstudio gCarreraDeEstudio =new GestionCarreraDeEstudio ();
     public static GestionEdificio gEdificio=new GestionEdificio();
     public static GestionEstudiante gEstudiante=new GestionEstudiante();
     public static GestionPeriodo gPeriodo=new GestionPeriodo();
     public static GestionProfesor gProfesor=new GestionProfesor();
          
    
    public MDIPrincipal() {
        initComponents();
        super.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuPeriodo = new javax.swing.JMenuItem();
        mnuCarreraEstudio = new javax.swing.JMenuItem();
        mnuEstudiante = new javax.swing.JMenuItem();
        mnuProfesor = new javax.swing.JMenuItem();
        mnuCampoEstudio = new javax.swing.JMenuItem();
        mnuEdificio = new javax.swing.JMenuItem();
        mnuAula = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        mnuPeriodo.setMnemonic('o');
        mnuPeriodo.setText("Periodo");
        mnuPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPeriodoActionPerformed(evt);
            }
        });
        fileMenu.add(mnuPeriodo);

        mnuCarreraEstudio.setMnemonic('s');
        mnuCarreraEstudio.setText("Carrera De Estudio");
        mnuCarreraEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarreraEstudioActionPerformed(evt);
            }
        });
        fileMenu.add(mnuCarreraEstudio);

        mnuEstudiante.setMnemonic('a');
        mnuEstudiante.setText("Estudiante");
        mnuEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstudianteActionPerformed(evt);
            }
        });
        fileMenu.add(mnuEstudiante);

        mnuProfesor.setText("Profesor");
        mnuProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProfesorActionPerformed(evt);
            }
        });
        fileMenu.add(mnuProfesor);

        mnuCampoEstudio.setText("Campo De Estudio");
        mnuCampoEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCampoEstudioActionPerformed(evt);
            }
        });
        fileMenu.add(mnuCampoEstudio);

        mnuEdificio.setText("Edificio");
        mnuEdificio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEdificioActionPerformed(evt);
            }
        });
        fileMenu.add(mnuEdificio);

        mnuAula.setText("Aula");
        mnuAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAulaActionPerformed(evt);
            }
        });
        fileMenu.add(mnuAula);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstudianteActionPerformed
        frmEstudiante frm1=new frmEstudiante();
        this.desktopPane.add(frm1);
        frm1.setVisible(true);
    }//GEN-LAST:event_mnuEstudianteActionPerformed

    private void mnuCarreraEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarreraEstudioActionPerformed
        frmCarreraEstudio frm1=new frmCarreraEstudio();
        this.desktopPane.add(frm1);
        frm1.setVisible(true);
    }//GEN-LAST:event_mnuCarreraEstudioActionPerformed

    private void mnuPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPeriodoActionPerformed
        frmPeriodo frm1=new frmPeriodo();
        this.desktopPane.add(frm1);
        frm1.setVisible(true);

    }//GEN-LAST:event_mnuPeriodoActionPerformed

    private void mnuProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProfesorActionPerformed
        frmProfesor frm1=new frmProfesor();
        this.desktopPane.add(frm1);
        frm1.setVisible(true);
    }//GEN-LAST:event_mnuProfesorActionPerformed

    private void mnuCampoEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCampoEstudioActionPerformed
        frmCampoEstudio frm1=new frmCampoEstudio();
        this.desktopPane.add(frm1);
        frm1.setVisible(true);
    }//GEN-LAST:event_mnuCampoEstudioActionPerformed

    private void mnuEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEdificioActionPerformed
         frmEdificio frm1=new frmEdificio();
        this.desktopPane.add(frm1);
        frm1.setVisible(true);
    }//GEN-LAST:event_mnuEdificioActionPerformed

    private void mnuAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAulaActionPerformed
        frmAula frm1=new frmAula();
        this.desktopPane.add(frm1);
        frm1.setVisible(true);
    }//GEN-LAST:event_mnuAulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuAula;
    private javax.swing.JMenuItem mnuCampoEstudio;
    private javax.swing.JMenuItem mnuCarreraEstudio;
    private javax.swing.JMenuItem mnuEdificio;
    private javax.swing.JMenuItem mnuEstudiante;
    private javax.swing.JMenuItem mnuPeriodo;
    private javax.swing.JMenuItem mnuProfesor;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
